# Generated by Django 4.2.3 on 2023-10-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('order', models.CharField(choices=[('Корпоративный', 'Корпоративный'), ('Индивидуальный', 'Индивидуальный'), ('Срочный', 'Срочный'), ('Предварительный', 'Предварительный')], max_length=100, verbose_name='Заказы')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Стоимость заказа')),
                ('start_of_order', models.DateField(verbose_name='Начало заказа')),
                ('end_of_order', models.DateField(verbose_name='Окончание заказа')),
                ('comment', models.TextField(verbose_name='Что вас интересует?')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Запросы на обратную связь',
            },
        ),
    ]
